#line 2 "lex.hat_karga.cc"

#line 4 "lex.hat_karga.cc"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer hat_karga_create_buffer
#define yy_delete_buffer hat_karga_delete_buffer
#define yy_flex_debug hat_karga_flex_debug
#define yy_init_buffer hat_karga_init_buffer
#define yy_flush_buffer hat_karga_flush_buffer
#define yy_load_buffer_state hat_karga_load_buffer_state
#define yy_switch_to_buffer hat_karga_switch_to_buffer
#define yyin hat_kargain
#define yyleng hat_kargaleng
#define yylex hat_kargalex
#define yylineno hat_kargalineno
#define yyout hat_kargaout
#define yyrestart hat_kargarestart
#define yytext hat_kargatext
#define yywrap hat_kargawrap
#define yyalloc hat_kargaalloc
#define yyrealloc hat_kargarealloc
#define yyfree hat_kargafree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE hat_kargarestart(hat_kargain  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int hat_kargaleng;

extern FILE *hat_kargain, *hat_kargaout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up hat_kargatext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up hat_kargatext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via hat_kargarestart()), so that the user can continue scanning by
	 * just pointing hat_kargain at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when hat_kargatext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int hat_kargaleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow hat_kargawrap()'s to do buffer switches
 * instead of setting up a fresh hat_kargain.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void hat_kargarestart (FILE *input_file  );
void hat_karga_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE hat_karga_create_buffer (FILE *file,int size  );
void hat_karga_delete_buffer (YY_BUFFER_STATE b  );
void hat_karga_flush_buffer (YY_BUFFER_STATE b  );
void hat_kargapush_buffer_state (YY_BUFFER_STATE new_buffer  );
void hat_kargapop_buffer_state (void );

static void hat_kargaensure_buffer_stack (void );
static void hat_karga_load_buffer_state (void );
static void hat_karga_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER hat_karga_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE hat_karga_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE hat_karga_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE hat_karga_scan_bytes (yyconst char *bytes,int len  );

void *hat_kargaalloc (yy_size_t  );
void *hat_kargarealloc (void *,yy_size_t  );
void hat_kargafree (void *  );

#define yy_new_buffer hat_karga_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        hat_kargaensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            hat_karga_create_buffer(hat_kargain,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        hat_kargaensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            hat_karga_create_buffer(hat_kargain,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define hat_kargawrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *hat_kargain = (FILE *) 0, *hat_kargaout = (FILE *) 0;

typedef int yy_state_type;

extern int hat_kargalineno;

int hat_kargalineno = 1;

extern char *hat_kargatext;
#define yytext_ptr hat_kargatext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up hat_kargatext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	hat_kargaleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 28
#define YY_END_OF_BUFFER 29
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[120] =
    {   0,
        0,    0,    0,    0,   29,   23,   20,   21,   23,   18,
        7,    8,   10,    9,    1,   11,    4,    1,    1,   23,
       12,   20,    1,    1,    1,    1,    7,   23,   23,   23,
       22,   22,    0,    0,   18,   18,    0,    0,    0,    0,
        0,    1,    4,    0,    1,    1,    0,    0,    3,    1,
        3,    1,    1,    1,   27,    0,    0,    0,    0,    5,
        0,    0,    0,    0,    0,    0,    1,    0,    3,    1,
        1,   25,    0,    0,    0,    0,    0,   17,    0,    0,
        0,   19,    0,    0,    3,    1,    0,    0,    0,    0,
        0,   25,   26,   16,    0,    0,    0,    0,    0,    3,

        3,   24,   24,    0,   15,    0,    0,    0,    3,    3,
       14,    0,    2,    6,    2,    0,    0,   13,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    5,    6,    7,    1,    1,    1,    8,
        9,   10,   11,    1,   12,   13,   14,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   16,    1,   17,
        1,   18,    7,    7,   19,   20,   21,   22,   23,   24,
       25,   26,   27,   22,   28,   29,   30,   22,   31,   22,
       22,   32,   33,   22,   22,   22,   22,   21,   22,   34,
       35,    7,    7,   35,   36,    1,   37,   37,   37,   37,

       37,   37,   37,   37,   37,   37,   37,   37,   37,   37,
       37,   37,   37,   37,   38,   37,   37,   37,   37,   37,
       37,   37,    1,   39,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,   37,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
       37,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[40] =
    {   0,
        1,    1,    2,    3,    1,    1,    4,    5,    6,    7,
        7,    7,    1,    1,    4,    1,    4,    4,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    4,    5,    9,    7,    4
    } ;

static yyconst flex_int16_t yy_base[135] =
    {   0,
        0,   39,   78,   97,  351,  480,  480,  480,  345,  117,
      100,  480,  480,  480,    0,  480,  334,  133,  169,    0,
      480,  123,  208,  247,  329,  321,  480,    0,  116,    0,
        0,  480,  341,  130,    0,  124,  326,  310,  312,  319,
      308,    0,  325,  329,  113,  130,  143,  309,    0,    0,
      286,  325,  129,  134,    0,  319,  142,  157,  313,  480,
      303,  318,  290,  291,  301,  149,  146,  300,  323,  155,
      135,  480,  171,  300,  176,  303,  307,  480,  285,  295,
      288,  480,  170,  280,  163,  183,  193,  293,  289,  296,
      295,  290,  480,  480,  282,  289,  278,  285,  274,  286,

        0,  292,  480,  241,  480,  176,  174,    0,  154,    0,
      480,  183,  189,    0,  193,  167,  150,  480,  480,  360,
      369,  372,  379,  386,  394,  403,  408,  416,  425,  434,
      443,  452,  461,  470
    } ;

static yyconst flex_int16_t yy_def[135] =
    {   0,
      119,  119,  119,    3,  119,  119,  119,  119,  120,  121,
      119,  119,  119,  119,  122,  119,  119,  123,  123,  124,
      119,  119,  119,  119,   24,   24,  119,  125,  126,  127,
      125,  119,  120,  120,  121,  121,  119,  119,  119,  119,
      119,  122,  119,  124,   19,   19,  119,  119,  128,   23,
      129,   24,   24,   24,  125,  126,  126,  130,  127,  119,
      119,  119,  119,  119,  119,  124,   19,  119,  129,   24,
       24,  119,  131,  132,  131,  119,  119,  119,  119,  119,
      119,  119,  124,  119,   69,   24,  131,  132,  131,  126,
      119,  132,  119,  119,  119,  119,  119,  124,  119,   69,

      133,  126,  119,  119,  119,  119,  124,  134,   69,  133,
      119,  119,  124,  134,   69,  119,  119,  119,    0,  119,
      119,  119,  119,  119,  119,  119,  119,  119,  119,  119,
      119,  119,  119,  119
    } ;

static yyconst flex_int16_t yy_nxt[520] =
    {   0,
        6,    7,    8,    7,    9,   10,    6,   11,   12,   13,
       14,    6,   15,   16,   17,    6,    6,    6,   18,   18,
       18,   18,   18,   18,   18,   19,   18,   18,   18,   18,
       18,   18,   18,   18,   20,    6,   15,   15,   21,    6,
       22,    8,   22,    9,   10,    6,   11,   12,   13,   14,
        6,   23,   16,   17,    6,    6,    6,   24,   24,   24,
       24,   24,   24,   24,   25,   24,   24,   24,   24,   26,
       24,   24,   24,   20,    6,   23,   23,   21,    6,    7,
        8,    7,    9,    6,    6,   27,   12,    6,    6,    6,
       28,   29,    6,    6,   30,    6,   28,   28,   28,   28,

       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   28,    6,    6,    6,    6,    6,   31,   36,   37,
       36,   66,   38,   39,   47,   36,   47,   36,   40,   57,
       41,   45,   58,   60,   34,   32,   44,   69,   66,   44,
       44,   44,   69,   69,   47,   72,   47,   44,   45,   44,
       44,   82,   71,   48,   66,   57,  119,   66,  118,   56,
       74,   70,   67,   69,   45,  119,   86,   44,   44,   42,
       75,   44,   44,   48,   88,   44,   44,   44,   66,   92,
      115,   83,   66,   44,   89,   44,   44,   46,   90,   89,
       85,   69,  100,   90,  117,  119,   88,   66,  101,   98,

      113,  116,  112,   44,   44,   42,   89,   44,   49,   49,
       90,   49,   49,   49,   49,   49,   49,   50,   50,   50,
       49,   49,   49,   49,   49,   49,   50,   50,   50,   50,
       50,   50,   50,   50,   50,   50,   50,   50,   50,   50,
       50,   50,   49,   49,   50,   50,   49,   49,   49,  111,
       51,   49,   49,   51,   51,   51,   52,   52,   52,   49,
       49,   51,   49,   51,   51,   52,   52,   52,   52,   52,
       52,   52,   52,   52,   52,   52,   52,   52,   52,   52,
       52,   51,   51,   50,   52,   51,   49,   49,  119,  108,
       49,   49,   92,   66,   69,   72,  106,  105,   49,   49,

      104,   49,   89,  107,  109,   57,   90,   91,  103,  102,
       91,   99,   97,   96,   95,   94,   93,   91,   84,   81,
       80,   79,   49,   49,   49,   82,   78,   49,   49,   77,
       76,   69,   57,   69,   68,   49,   49,   66,   49,   43,
       65,   64,   63,   62,   61,   34,   54,   53,   43,   34,
      119,  119,  119,  119,  119,  119,  119,  119,  119,   49,
       33,   33,  119,   33,   33,   33,   33,   33,   33,   35,
      119,   35,   35,   35,   35,   35,   35,   35,   42,   42,
       42,   45,   45,   45,   45,   45,   45,   45,   44,   44,
       44,   44,   44,   44,   55,   55,   55,   55,   55,  119,

       55,   55,   55,   56,   56,  119,   56,   56,   56,   56,
       56,   56,   59,   59,  119,   59,   49,  119,   49,   49,
       49,   49,   49,   49,   49,   51,  119,   51,   51,   51,
       51,   51,   51,   51,   73,   73,   73,   73,   73,   73,
       73,   73,   73,   87,   87,   87,   87,   87,   87,   87,
       87,   87,   88,   88,   88,   88,   88,   88,   88,   88,
       88,  110,  119,  110,  110,  110,  110,  110,  110,  110,
      114,  119,  114,  114,  114,  114,  114,  114,  114,    5,
      119,  119,  119,  119,  119,  119,  119,  119,  119,  119,
      119,  119,  119,  119,  119,  119,  119,  119,  119,  119,

      119,  119,  119,  119,  119,  119,  119,  119,  119,  119,
      119,  119,  119,  119,  119,  119,  119,  119,  119
    } ;

static yyconst flex_int16_t yy_chk[520] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,

        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    4,   10,   11,
       10,   45,   11,   11,   22,   36,   22,   36,   11,   29,
       11,   45,   29,   34,   34,    4,   18,   53,   46,   18,
       18,   18,   54,   71,   47,   57,   47,   18,   46,   18,
       18,   66,   54,   22,   67,   57,  109,   66,  117,   58,
       58,   53,   46,   70,   67,   85,   71,   18,   18,   18,
       58,   18,   19,   47,   73,   19,   19,   19,   83,   75,
      109,   67,  107,   19,   73,   19,   19,   19,   73,   75,
       70,   86,   85,   75,  116,  115,   87,  113,   86,   83,

      107,  112,  106,   19,   19,   19,   87,   19,   23,   23,
       87,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   24,   24,  104,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   51,   51,  100,   99,
       51,   51,   89,   98,   51,  102,   97,   96,   51,   51,

       95,   51,   89,   98,  100,  102,   89,   92,   91,   90,
       88,   84,   81,   80,   79,   77,   76,   74,   68,   65,
       64,   63,   51,   69,   69,   69,   62,   69,   69,   61,
       59,   69,   56,   52,   48,   69,   69,   44,   69,   43,
       41,   40,   39,   38,   37,   33,   26,   25,   17,    9,
        5,    0,    0,    0,    0,    0,    0,    0,    0,   69,
      120,  120,    0,  120,  120,  120,  120,  120,  120,  121,
        0,  121,  121,  121,  121,  121,  121,  121,  122,  122,
      122,  123,  123,  123,  123,  123,  123,  123,  124,  124,
      124,  124,  124,  124,  125,  125,  125,  125,  125,    0,

      125,  125,  125,  126,  126,    0,  126,  126,  126,  126,
      126,  126,  127,  127,    0,  127,  128,    0,  128,  128,
      128,  128,  128,  128,  128,  129,    0,  129,  129,  129,
      129,  129,  129,  129,  130,  130,  130,  130,  130,  130,
      130,  130,  130,  131,  131,  131,  131,  131,  131,  131,
      131,  131,  132,  132,  132,  132,  132,  132,  132,  132,
      132,  133,    0,  133,  133,  133,  133,  133,  133,  133,
      134,    0,  134,  134,  134,  134,  134,  134,  134,  119,
      119,  119,  119,  119,  119,  119,  119,  119,  119,  119,
      119,  119,  119,  119,  119,  119,  119,  119,  119,  119,

      119,  119,  119,  119,  119,  119,  119,  119,  119,  119,
      119,  119,  119,  119,  119,  119,  119,  119,  119
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int hat_karga_flex_debug;
int hat_karga_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *hat_kargatext;
#line 1 "hat_karga.l"
#line 2 "hat_karga.l"
extern "C"
{
int hat_kargalex(void);
}

#include "hat_karga.tab.hh"
#include <stdio.h>
#include <string.h>
#include "bereiz_etq.h"

int puntuazioa_da(char *etq)
{
 if ((strcmp(etq,PUNTUA) == 0) ||
     (strcmp(etq,GALDERA) == 0) ||
     (strcmp(etq,PUNTU_KOMA) == 0) ||
     (strcmp(etq,ESKLAM) == 0) ||
     (strcmp(etq,BI_PUNTU) == 0))
   return 1;
 return 0;
}


int amaitu_bidalia=0;

YY_BUFFER_STATE bStateHat;
extern char *testu_buffer;
extern int buffer_size;

extern FILE *irteera_fitx;
extern int TARTEKATU;
extern int line;


#line 670 "lex.hat_karga.cc"

#define INITIAL 0
#define testua 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int hat_kargalex_destroy (void );

int hat_kargaget_debug (void );

void hat_kargaset_debug (int debug_flag  );

YY_EXTRA_TYPE hat_kargaget_extra (void );

void hat_kargaset_extra (YY_EXTRA_TYPE user_defined  );

FILE *hat_kargaget_in (void );

void hat_kargaset_in  (FILE * in_str  );

FILE *hat_kargaget_out (void );

void hat_kargaset_out  (FILE * out_str  );

int hat_kargaget_leng (void );

char *hat_kargaget_text (void );

int hat_kargaget_lineno (void );

void hat_kargaset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int hat_kargawrap (void );
#else
extern int hat_kargawrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( hat_kargatext, hat_kargaleng, 1, hat_kargaout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( hat_kargain )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( hat_kargain ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, hat_kargain))==0 && ferror(hat_kargain)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(hat_kargain); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int hat_kargalex (void);

#define YY_DECL int hat_kargalex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after hat_kargatext and hat_kargaleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( hat_kargaleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(hat_kargatext[hat_kargaleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 56 "hat_karga.l"

#line 863 "lex.hat_karga.cc"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! hat_kargain )
			hat_kargain = stdin;

		if ( ! hat_kargaout )
			hat_kargaout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			hat_kargaensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				hat_karga_create_buffer(hat_kargain,YY_BUF_SIZE );
		}

		hat_karga_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of hat_kargatext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 120 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 480 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 57 "hat_karga.l"
{
                    hat_kargalval.str[0] = '\0';
                    strcpy(hat_kargalval.str,hat_kargatext);
                    return HITZA;
                   }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 62 "hat_karga.l"
{
                    hat_kargalval.str[0] = '\0';
                    strcpy(hat_kargalval.str,hat_kargatext);
                    return ETIK_HAUL;
                   }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 67 "hat_karga.l"
{
                    int i=0;

                    while ((hat_kargatext[i]==' ') || (hat_kargatext[i] == '\t'))
                      /*** hasierako zuriguneak kendu */
                      i++;
                    hat_kargalval.str[0] = '\0';
                    strcpy(hat_kargalval.str,&hat_kargatext[i]);
                    i = strlen(hat_kargalval.str)-1;
                    while ((hat_kargalval.str[i] == ' ') || (hat_kargalval.str[i] == '\t'))
                      /*** bukaerako zuriguneak kendu */
                       i--;
                    hat_kargalval.str[i+1] = '\0';
                    return HAT_LEMA;
                   }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 82 "hat_karga.l"
{
                    sscanf(hat_kargatext,"%d",&hat_kargalval.zif);
                    return ZIFRA;
                   }
	YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 86 "hat_karga.l"
{
                    hat_kargalval.str[0] = '\0';
                    strcpy(hat_kargalval.str,&hat_kargatext[1]); /*** hasierako " kenduta */
                    /* hasierako \" kenduta */
                    hat_kargalval.str[strlen(hat_kargalval.str)-2] = '\0';
                    /* bukaerako \" eta zuriunea kenduta */
                    return LEMAA;
                   }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 94 "hat_karga.l"
{
                    int i=0;

                    while ((hat_kargatext[i]==' ') || (hat_kargatext[i] == '\t'))
                      /*** hasierako zuriguneak kendu */
                      i++;
                    hat_kargalval.str[0] = '\0';
                    strcpy(hat_kargalval.str,&hat_kargatext[i]);
                    i = strlen(hat_kargalval.str)-1;
                    while ((hat_kargalval.str[i] == ' ') || (hat_kargalval.str[i] == '\t'))
                      /*** bukaerako zuriguneak kendu */
                       i--;
                    hat_kargalval.str[i+1] = '\0';
                    return OHARRA;
                   }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 109 "hat_karga.l"
{
                    return PAR_IREKI;
                   }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 112 "hat_karga.l"
{
                    return PAR_ITXI;
                   }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 115 "hat_karga.l"
{
                    return ERROA;
                   }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 118 "hat_karga.l"
{
                    return ETENA;
                   }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 121 "hat_karga.l"
{
                    return EZORD;
                   }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 124 "hat_karga.l"
{
                    return PIPE;
                   }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 127 "hat_karga.l"
{
                    return OSAGAI_KOP;
                   }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 130 "hat_karga.l"
{
                    return FORMA_DA;
                   }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 133 "hat_karga.l"
{
                    return LEMA_DA;
                   }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 136 "hat_karga.l"
{
                    return BAI;
                   }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 139 "hat_karga.l"
{
                    return EZ;
                   }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 142 "hat_karga.l"
{
                    int i=1; /*** lehen posizio # */

                    while ((hat_kargatext[i]==' ') || (hat_kargatext[i] == '\t'))
                      /*** hasierako zuriguneak kendu */
                      i++;
                    hat_kargalval.str[0] = '\0';
                    if (hat_kargatext[i] != '\0')
                      strcpy(hat_kargalval.str,&hat_kargatext[i]);
                    i = strlen(hat_kargalval.str)-1;
                    while ((hat_kargalval.str[i] == ' ') || (hat_kargalval.str[i] == '\t'))
                      /*** bukaerako zuriguneak kendu */
                       i--;
                    hat_kargalval.str[i+1] = '\0';
                    return HAT_INFO;
                   }
	YY_BREAK
case 19:
*yy_cp = (yy_hold_char); /* undo effects of setting up hat_kargatext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up hat_kargatext again */
YY_RULE_SETUP
#line 158 "hat_karga.l"
{
                    int i=0;
                    yyless(hat_kargaleng-1);
                    while ((hat_kargatext[i]==' ') || (hat_kargatext[i] == '\t'))
                      /*** hasierako zuriguneak kendu */
                      i++;
                    hat_kargalval.str[0] = '\0';
                    strcpy(hat_kargalval.str,&hat_kargatext[i]);
                    i = strlen(hat_kargalval.str)-1;
                    while ((hat_kargalval.str[i] == ' ') || (hat_kargalval.str[i] == '\t'))
                      /*** bukaerako zuriguneak kendu */
                       i--;
                    hat_kargalval.str[i+1] = '\0';
                    return INFORMAZIOA;
                   }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 173 "hat_karga.l"
{
                   hat_kargaout = irteera_fitx;
                   fclose(hat_kargain);

                   bStateHat = hat_karga_scan_buffer(testu_buffer,buffer_size);
                   hat_karga_switch_to_buffer(bStateHat); 

                   BEGIN(testua);
                   line = 1;
                 }
	YY_BREAK
case YY_STATE_EOF(testua):
#line 183 "hat_karga.l"
{
                    if (amaitu_bidalia) { 
                      hat_karga_delete_buffer(bStateHat); 
                      fclose(hat_kargaout);
                      return hat_kargatext[0];
                    }
                    else {
                      amaitu_bidalia = 1;
                      return AMAITU;
                    }
                 }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 195 "hat_karga.l"
{ 
                        }
	YY_BREAK
case 21:
/* rule 21 can match eol */
YY_RULE_SETUP
#line 197 "hat_karga.l"
{ 
                          line++;
                        }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 200 "hat_karga.l"
{
                         return CORRECT;
                        }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 203 "hat_karga.l"
{
                        return hat_kargatext[0];
                        }
	YY_BREAK
case 24:
/* rule 24 can match eol */
YY_RULE_SETUP
#line 206 "hat_karga.l"
{
               hat_kargalval.str[0] = '\0';
               strcpy(hat_kargalval.str,&hat_kargatext[2]);
               /* hasierako /< kenduta */
               hat_kargalval.str[strlen(hat_kargalval.str)-2] = '\0';
               /* bukaerako >/ kenduta */
               return HITZ_FORMA;
              }
	YY_BREAK
case 25:
/* rule 25 can match eol */
YY_RULE_SETUP
#line 214 "hat_karga.l"
{
               hat_kargalval.str[0] = '\0';
               strcpy(hat_kargalval.str,&hat_kargatext[1]); /*** / */
               /* hasierako / kenduta */
               hat_kargalval.str[strlen(hat_kargalval.str)-2] = '\0';
               /* bukaerako / eta txuria kenduta */
               return ALDAERA;
              }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 222 "hat_karga.l"
{
               hat_kargalval.str[0] = '\0';
               strcpy(hat_kargalval.str,&hat_kargatext[1]);
               /* hasierako < kenduta */
               hat_kargalval.str[strlen(hat_kargalval.str)-2] = '\0';
               /* bukaerako >/ kenduta */
               if (puntuazioa_da(hat_kargalval.str))
                 return ETIK_PUNT;
               return ETIK;
              }
	YY_BREAK
case 27:
/* rule 27 can match eol */
YY_RULE_SETUP
#line 232 "hat_karga.l"
{
               hat_kargalval.str[0] = '\0';
               strcpy(hat_kargalval.str,hat_kargatext);
               return INFORMAZIOA;
              }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 237 "hat_karga.l"
ECHO;
	YY_BREAK
#line 1253 "lex.hat_karga.cc"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed hat_kargain at a new source and called
			 * hat_kargalex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = hat_kargain;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( hat_kargawrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * hat_kargatext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of hat_kargalex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					hat_kargarealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			hat_kargarestart(hat_kargain  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) hat_kargarealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 120 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 120 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 119);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up hat_kargatext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					hat_kargarestart(hat_kargain );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( hat_kargawrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve hat_kargatext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void hat_kargarestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        hat_kargaensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            hat_karga_create_buffer(hat_kargain,YY_BUF_SIZE );
	}

	hat_karga_init_buffer(YY_CURRENT_BUFFER,input_file );
	hat_karga_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void hat_karga_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		hat_kargapop_buffer_state();
	 *		hat_kargapush_buffer_state(new_buffer);
     */
	hat_kargaensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	hat_karga_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (hat_kargawrap()) processing, but the only time this flag
	 * is looked at is after hat_kargawrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void hat_karga_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	hat_kargain = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE hat_karga_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) hat_kargaalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in hat_karga_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) hat_kargaalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in hat_karga_create_buffer()" );

	b->yy_is_our_buffer = 1;

	hat_karga_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with hat_karga_create_buffer()
 * 
 */
    void hat_karga_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		hat_kargafree((void *) b->yy_ch_buf  );

	hat_kargafree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a hat_kargarestart() or at EOF.
 */
    static void hat_karga_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	hat_karga_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then hat_karga_init_buffer was _probably_
     * called from hat_kargarestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void hat_karga_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		hat_karga_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void hat_kargapush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	hat_kargaensure_buffer_stack();

	/* This block is copied from hat_karga_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from hat_karga_switch_to_buffer. */
	hat_karga_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void hat_kargapop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	hat_karga_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		hat_karga_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void hat_kargaensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)hat_kargaalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in hat_kargaensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)hat_kargarealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in hat_kargaensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE hat_karga_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) hat_kargaalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in hat_karga_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	hat_karga_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to hat_kargalex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       hat_karga_scan_bytes() instead.
 */
YY_BUFFER_STATE hat_karga_scan_string (yyconst char * yystr )
{
    
	return hat_karga_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to hat_kargalex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE hat_karga_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) hat_kargaalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in hat_karga_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = hat_karga_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in hat_karga_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up hat_kargatext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		hat_kargatext[hat_kargaleng] = (yy_hold_char); \
		(yy_c_buf_p) = hat_kargatext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		hat_kargaleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int hat_kargaget_lineno  (void)
{
        
    return hat_kargalineno;
}

/** Get the input stream.
 * 
 */
FILE *hat_kargaget_in  (void)
{
        return hat_kargain;
}

/** Get the output stream.
 * 
 */
FILE *hat_kargaget_out  (void)
{
        return hat_kargaout;
}

/** Get the length of the current token.
 * 
 */
int hat_kargaget_leng  (void)
{
        return hat_kargaleng;
}

/** Get the current token.
 * 
 */

char *hat_kargaget_text  (void)
{
        return hat_kargatext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void hat_kargaset_lineno (int  line_number )
{
    
    hat_kargalineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see hat_karga_switch_to_buffer
 */
void hat_kargaset_in (FILE *  in_str )
{
        hat_kargain = in_str ;
}

void hat_kargaset_out (FILE *  out_str )
{
        hat_kargaout = out_str ;
}

int hat_kargaget_debug  (void)
{
        return hat_karga_flex_debug;
}

void hat_kargaset_debug (int  bdebug )
{
        hat_karga_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from hat_kargalex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    hat_kargain = stdin;
    hat_kargaout = stdout;
#else
    hat_kargain = (FILE *) 0;
    hat_kargaout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * hat_kargalex_init()
     */
    return 0;
}

/* hat_kargalex_destroy is for both reentrant and non-reentrant scanners. */
int hat_kargalex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		hat_karga_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		hat_kargapop_buffer_state();
	}

	/* Destroy the stack itself. */
	hat_kargafree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * hat_kargalex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *hat_kargaalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *hat_kargarealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void hat_kargafree (void * ptr )
{
	free( (char *) ptr );	/* see hat_kargarealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 237 "hat_karga.l"



